name: 'Modified AWS ECS "Render Task Definition" Action for GitHub Actions'
description: 'Allows modification of attributes in an Amazon ECS task definition JSON file, creating a new file.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The path to the ECS task definition JSON file'
    required: true
  container-name:
    description: 'The name of the container defined in the containerDefinitions section of the ECS task definition. Required if image or  is present'
    required: false
  container-attrs:
    description: 'A hash (as a json string) of key values to set on the container definition, e.g. image, name, cpu, etc'
    required: false
  remove-containers:
    description: 'An array (as a json string) of container names to be removed from the task definition'
    required: false
outputs:
  task-definition:
    description: 'The path to the rendered task definition file'
runs:
  using: 'node12'
  main: 'dist/index.js'
